apiVersion: v1
kind: ConfigMap
metadata:
  name: lp-config
data:
  config.yml: |
    grpc_server:
      address: ":8002"
      timeout: "2s"
    storage:
      type: postgres
      host: postgres
      port: 5432
      user: postgres
      password: postgres
      dbname: postgres
    rabbit_mq:
      username: guest
      password: guest
      host: rabbitmq
      port: 5672
      channel:
        channel_consumer:
          queue: channel
          consumer: ""
          autoAck: false
          exclusive: false
          noLocal: false
          noWait: false
          args:
            x-consumer-timeout: 60000
            x-consumer-prefetch-count: 5
      plan:
        plan_consumer:
          queue: plan
          consumer: ""
          autoAck: false
          exclusive: false
          noLocal: false
          noWait: false
          args:
            x-consumer-timeout: 60000
            x-consumer-prefetch-count: 5
      spfu:
        spfu_consumer:
          queue: spfu
          consumer: ""
          autoAck: false
          exclusive: false
          noLocal: false
          noWait: false
          args:
            x-consumer-timeout: 60000
            x-consumer-prefetch-count: 5
    redis:
      host: redis
      port: 6379
      attemts_db: 3
      password: ""
    clients:
      sso:
        address: "sso-app-service:50051"
        timeout: "2s"
        retries_count: 3
        insecure: false