grpc_server:
  address: ":8002"
  timeout: "2s"
storage:
  type: "postgres"
  host: "localhost"
  port: 5435
  user: "postgres"
  password: "postgres"
  dbname: "postgres"
rabbit_mq:
  username: guest
  password: guest
  host: localhost
  port: 5672
  channel:
    channel_consumer:
      queue: channel
      consumer: ""
      autoAck: false
      exclusive: false
      noLocal: false
      noWait: false
      args:
        x-consumer-timeout: 60000
        x-consumer-prefetch-count: 5
  plan:
    plan_consumer:
      queue: plan
      consumer: ""
      autoAck: false
      exclusive: false
      noLocal: false
      noWait: false
      args:
        x-consumer-timeout: 60000
        x-consumer-prefetch-count: 5
  spfu:
    spfu_consumer:
      queue: spfu
      consumer: ""
      autoAck: false
      exclusive: false
      noLocal: false
      noWait: false
      args:
        x-consumer-timeout: 60000
        x-consumer-prefetch-count: 5
redis:
  host: localhost
  port: 6379
  attemts_db: 3
  password: ""
clients:
  sso:
    address: ":8081"
    timeout: "2s"
    retries_count: 3
    insecure: false