grpc_server:
  address: ":8081"
  timeout: "2s"
mongo_db:
  url: "mongodb://root:example@localhost:27017/db_sso"
  host: localhost
  db_name: db_sso
  username: test
  password: test
rabbit_mq:
  username: guest
  password: guest
  host: localhost
  port: 5672
  chat:
    chat_consumer:
      queue: chat_id
      consumer: ""
      autoAck: false
      exclusive: false
      noLocal: false
      noWait: false
      args:
        x-consumer-timeout: 60000
        x-consumer-prefetch-count: 5
  notification:
    notification_consumer:
      queue: notification_to_auth
      consumer: ""
      autoAck: false
      exclusive: false
      noLocal: false
      noWait: false
      args:
        x-consumer-timeout: 60000
        x-consumer-prefetch-count: 5
    notification_routing_key: notification
redis:
  host: localhost
  port: 6379
  token_db: 0
  otp_db: 1
  password: ""
jwt:
  issuer: auth-service
  access_expires_in: 10h
  refresh_expires_in: 30h
  public_key: ./public_key.pem   
  private_key: ./private_key.pem